- name: Create Mealie Data Dir
  ansible.builtin.file:
    path: /opt/mealie/data
    state: directory
    recurse: yes
    owner: foo
    group: foo

- name: Install Mealie Compose File
  ansible.builtin.template:
    src: templates/docker-compose.yaml.jinja
    dest: /opt/mealie
    vars:
      docker_tag: v3.22.0

- name: Start Mealie
  community.docker.docker_compose_v2:
    project_src: /opt/mealie
    state: present
