- name: Create Mealie data directory
  ansible.builtin.file:
    path: /opt/mealie/data
    state: directory
    recurse: true
    owner: foo
    group: foo

- name: Build Mealie Docker-Compose file
  ansible.builtin.template:
    src: templates/docker-compose.yaml.jinja
    dest: /opt/mealie
    mode: "0755"

- name: Start Mealie
  community.docker.docker_compose_v2:
    project_src: /opt/mealie
    state: present
