- hosts: mealie
  tasks:
    # Connects to Proxmox to do work
    - name: Create VM
      ansible.builtin.include_role:
        name: proxmox-kvm
        vars:
          name: mealie
          cores: 2
          vcpus: 1
          memory: 2048

    # Connects to new VM to do work
    - name: Install common stuff
      ansible.builtin.include_role:
        name: common

    - name: Install Docker
      ansible.builtin.include_role:
        name: docker-engine

    - name: Install Mealie
      ansible.builtin.include_role:
        name: mealie
