# Playbook for Mealie deployment
- name: Deploy Mealie
  hosts: mealie
  tasks:
    # Connects to Proxmox to do work
    - name: Create VM
      ansible.builtin.include_role:
        name: proxmox_kvm
      vars:
        name: Mealie
        memory: 2048
        balloon: 0
        cores: 1
        vcpus: 1
        bios: ovmf
        machine: q35
        scsi:
        net:
          net0: virtio,bridge=opnbr0,firewall=1
        scsihw: virtio-scsi-single
        efidisk0:
          efitype: 4m
          pre_enrolled_keys: 1
    # Connects to new VM to do work
    - name: Install default packages
      ansible.builtin.include_role:
        name: common
    - name: Install Docker Engine
      ansible.builtin.include_role:
        name: docker_engine
    - name: Build Mealie container
      ansible.builtin.include_role:
        name: mealie
