- name: Update cache and upgrade OS
  become: true
  become_user: root
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
- name: Install common packages
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - sudo
      - qemu-guest-agent
      # Insert additional packages here as needed
    state: present
- name: Make default user a sudoer
  become: true
  become_user: root
  ansible.builtin.user:
    name: '{{ default_user }}'
    shell: /bin/bash
    groups: sudo
    append: true
    create_home: true
    state: present
